tmux send-keys -t s1 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 1.0 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s2 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.8 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s3 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.6 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s4 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.4 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s5 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.2 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s6 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.0 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s7 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 1.0 --seed 2 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s8 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.8 --seed 2 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s9 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.6 --seed 2 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s10 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.4 --seed 2 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s11 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.2 --seed 2 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
tmux send-keys -t s12 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.0 --seed 2 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
# tmux send-keys -t s13 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.8 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
# tmux send-keys -t s14 'conda activate mbpo && cd ~/mbpo_res &&  python run_mopo.py python main_mbpo.py --ratio_residual 0.6 --seed 1 --env_name "Hopper-v2" --model_train_freq 25 --num_epoch 300 --rollout_batch_size 1000 --epoch_length 100' C-m
